### ISSUE TITLE
Expose pipeline run metadata to Tasks and Conditions

### ISSUE THREAD

**Issue by dibyom** [tektoncd/pipeline#1020]
Condition containers need access to metadata about the pipeline run. The metadata will be in the form of  a `pr-metadata.json` file that is present in the `workspace` directory.

Part of implementation of #27

ref: https://github.com/tektoncd/pipeline/issues/1137

**Comment by bobcatfish** [comment]
@dibyom are you still working on this or can we throw it back in the backlog?

**Comment by dibyom** [comment]
> @dibyom are you still working on this or can we throw it back in the backlog?

Thanks for the reminder. Moved to backlog -- here's why:

1. There is a workaround that @akihikokuroda mentioned in the design doc: https://github.com/tektoncd/pipeline/issues/1016#issuecomment-542388985

2. The injected pipelinerun status is likely to be stale if there are parallel taskruns -- to counter the user would have to resort to the workaound above

3. Probably not going to be useful until we have #1376 as well.

I think we should take another look at this post #1376

**Comment by pritidesai** [comment]
This feature is essential for `finally`,  final tasks are executed after all Pipeline Tasks are finished executing with success or after a single Pipeline Task fails. The scope of this design goes beyond just conditional containers, and applies to all final task containers and possibly all pipeline task containers.

[Design Doc](https://docs.google.com/document/d/1lxpYQHppiWOxsn4arqbwAFDo4T0-LCqpNa6p-TJdHrw/edit?disco=AAAAJcDWe48)

@dibyom I would like to collaborate on the design, planning on working on it after core `finally` functionality is merged (PR #2650 and PR #2661). Looking at the design right now 👀 

/assign

**Comment by dibyom** [comment]
Excellent!! 😃 
I had a old [proposal](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit#heading=h.2f7asw3l4lo9) though I am not sure how much of that is still relevant especially with finally containers! Feel free to suggest something different it that makes more sense!

**Comment by bobcatfish** [comment]
I think @dibyom 's proposal to provide this info via json file is a great first step toward what we need for both conditions + finally. We can always follow that up with more power around variable interpolation if needed.

**Comment by pritidesai** [comment]
@popcor255 do you have any particular use case or story you would like to be supported with this feature request?

**Comment by popcor255** [comment]
@pritidesai Yes, as a user I would like to log my pipelines with something with logDNA/ELK. However, [this](https://github.com/tektoncd/pipeline/issues/1016#issuecomment-542388985) work around looks like I should be able to get the name of the pipelinerun I am under. This should let me kubctl against the params. :smile:

**Comment by sbwsg** [comment]
not sure if this has been discussed elsewhere but the pipeline run's name is also available as a context variable in Pipelines which you can then pass to Tasks as a param. see the using_context_variables example: https://github.com/tektoncd/pipeline/blob/master/examples/v1beta1/pipelineruns/using_context_variables.yaml#L30-L34

**Comment by pritidesai** [comment]
I am narrowing down the scope here:

## Goal

Access to execution status of other `taskRuns` within the same `Pipeline`.

## Proposal

Introduce execution status as a context variable (thanks @sbwsg for pointing out about context variables) in the form of `$(context.pipelineRun.Tasks.<pipelineTaskName>)"`. This variable can have one of the following values:

1. Started: taskRun for that pipelineTask has just started
2. Running: taskRun for that pipelineTask is running
3. Succeeded: taskRun for that pipelineTask completed successfully
4. Failed: taskRun for that pipelineTask completed with a failure
5. TaskRunCancelled: taskRun for that pipelineTask is cancelled by the user
6. TaskRunTimeout: taskRun for that pipelineTask has timed out
7. Unknown: no information available on that pipelineTask execution

## Usage  

```
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: test-pipelinerun-
spec:
  serviceAccountName: 'default'
  pipelineSpec:
    tasks:
    - name: task1
      params:
      taskSpec:
        steps:
        - image: ubuntu
          name: hello
          script: |
            echo "Hello World!"
    - name: task2
      runAfter: [ "task1" ]
      params:
        - name: pipelineRun-pipelineTask-task1
          value: "$(context.pipelineRun.Tasks.task1)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task1
        steps:
          - image: ubuntu
            name: print-task1-execution-status-and-fail
            script: |
              echo "Pipeline Task Status Task1: $(params.pipelineRun-pipelineTask-task1)"
              exit 1
    - name: task3
      runAfter: [ "task2" ]
      params:
        - name: pipelineRun-pipelineTask-task1
          value: "$(context.pipelineRun.Tasks.task1)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task1
        steps:
          - image: ubuntu
            name: print-task1-execution-status
            script: |
              echo "Pipeline Task Status Task1: $(params.pipelineRun-pipelineTask-task1)"
    finally:
    - name: task4
      params:
        - name: pipelineRun-pipelineTask-task2
          value: "$(context.pipelineRun.Tasks.task2)"
      taskSpec:
        params:
          - name: pipelineRun-pipelineTask-task2
        steps:
          - image: ubuntu
            name: print-failed-task-status
            script: |
              echo "Pipeline Task Status: Task2:  $(params.pipelineRun-pipelineTask-task2)"
```

Will add more details but before that, wanted to get feedback if this proposal is heading in right direction and would solve the use case we have today.

**Comment by jrcast** [comment]
@pritidesai what do you think about adding a status field for the pipelinerun itself? That way we can easily check for the pipelinerun state as part of a _generic_ `finally` task which we can reuse across pipelines regardless of which tasks we reference. Maybe you can follow the "True", "False", "Unknown" approach as seen [here](https://tekton.dev/docs/pipelines/pipelineruns/#monitoring-execution-status) or spell out the `Reason` or both 🤷 

Imagine, something like: 
```yaml
    finally:
    - name: notify-results
      params:
        - name: pipelineRunStatus
          value: "$(context.pipelineRun.status)"  
        - name: pipelineRunStatusReason
          value: "$(context.pipelineRun.reason)" 
      taskSpec:
        params:
          - name: pipelineRunStatus
        steps:
          - image: ubuntu
            name: notify-status
            script: |
              if [ $(params.pipelineRunStatus) == "True" ]
              then
                echo "PipelineRun was successful. Status was marked as  $(params.pipelineRunStatusReason)"
              else
                echo "PipelineRun Failed. Status was marked as  $(params.pipelineRunStatusReason)"
              fi
```

**Comment by pritidesai** [comment]
hey @jrcast I am not sure how `pipelineRun` status can be helpful here? `finally` is part of the same run and `pipelineRun` status is set to `running` until the pipeline finishes execution i.e. until finishes executing `finally` tasks. 

Also, I have [TEP](https://github.com/tektoncd/community/blob/108662a77fba2b2208cf849ba202e0a674c97a16/teps/0027-task-execution-status-at-runtime.md) created for this if you want to take a look 🙏

**Comment by verokarhu** [comment]
> I am narrowing down the scope here:
> 
> ## Goal
> Access to execution status of other `taskRuns` within the same `Pipeline`.
> 
> ## Proposal
> Introduce execution status as a context variable (thanks @sbwsg for pointing out about context variables) in the form of `$(context.pipelineRun.Tasks.<pipelineTaskName>)"`. This variable can have one of the following values:
> 
> 1. Succeeded: taskRun for that pipelineTask completed successfully
> 2. Failed: taskRun for that pipelineTask completed with a failure
> 3. TaskRunCancelled: taskRun for that pipelineTask is cancelled by the user
> 4. Skipped: that pipelineTask is skipped
> 5. Unknown: no information available on that pipelineTask execution
> 
> ## Usage
> ```
> kind: PipelineRun
> apiVersion: tekton.dev/v1beta1
> metadata:
>   generateName: test-pipelinerun-
> spec:
>   serviceAccountName: 'default'
>   pipelineSpec:
>     tasks:
>     - name: task1
>       params:
>       taskSpec:
>         steps:
>         - image: ubuntu
>           name: hello
>           script: |
>             echo "Hello World!"
>     - name: task2
>       runAfter: [ "task1" ]
>       taskSpec:
>         steps:
>           - image: ubuntu
>             name: fail
>             script: |
>               exit 1
>     finally:
>     - name: task3
>       params:
>         - name: pipelineRun-pipelineTask-task2
>           value: "$(context.pipelineRun.Tasks.task2)"
>       taskSpec:
>         params:
>           - name: pipelineRun-pipelineTask-task2
>         steps:
>           - image: ubuntu
>             name: print-failed-task-status
>             script: |
>               if [ $(params.pipelineRun-pipelineTask-task2) == "Failed" ]
>               then
>                 echo "Task2 has failed, continue processing the failure"
>               fi
> ```
> 
> Will add more details but before that, wanted to collect feedback if this proposal is heading in right direction and would solve the use cases we have today.

Most of my pipelines are at least 5 tasks, there are a few that are over 10. Configuring a finally task for e.g. reporting build status would be complicated as it would have to take the result of each single task as an input. It would also have to be customised for each pipeline and if someone adds a task they need to remember to update the finally task.

I think the idea @jrcast presented is in the right direction. We need a way to get the aggregated results of all the tasks without having to specify each single task. It would also make the finally task more reusable.

**Comment by pritidesai** [comment]
@verokarhu, the idea @jrcast presented about reading the `pipelineRun` status does not work since when the `finally` tasks are starting to execute, the `pipelineRun` status would be still `running` not `succeeded` or `failed` as `pipelineRun` status also includes status from `finally` tasks and not considered completed/done until `finally` tasks finish executing i.e. `pipelineRun` status does not represent aggregate status/results of all `tasks` under `tasks` section.

In addition to getting individual task execution status, we could add another context variable to get the aggregate results of all tasks using `$(context.pipelineRun.Tasks.status)` set to `succeeded` or `failed` , thoughts?

**Comment by pritidesai** [comment]
Also, the overall idea here is to include these context variables as by default available instead of explicitly mapping in future.

**Comment by jrcast** [comment]
> In addition to getting individual task execution status, we could add another context variable to get the aggregate results of all tasks using `$(context.pipelineRun.Tasks.status)` set to `succeeded` or `failed` , thoughts?

I think the aggregate results of _all_ tasks would do the trick. If all tasks are, let's say, `suceeded`, then  `$(context.pipelineRun.Tasks.status)` should be `succeeded` right?. If one of the tasks is `failed` then the aggregate should be `failed`. I think something like this would still allow to reuse the finally task regardless of the pipeline in question without having to write and maintain such finally task each time the pipeline `tasks` change.

**Comment by pritidesai** [comment]
> If all tasks are, let's say, suceeded, then $(context.pipelineRun.Tasks.status) should be succeeded or True right?. If any one of the tasks is failed or equivalent, then the aggregate should be failed or False.

Yes and as the variable says `tasks`, this does not include any of the `finally` tasks.

I will think of alternate name to avoid any confusion, otherwise, this sounds good.

**Comment by pritidesai** [comment]
@vdemeester this is the use case I was referring to about accessing aggregate execution status of all `tasks` in `finally.

**Comment by riceluxs1t** [comment]
Hi. We also have a use case where a Tekton pipeline consists of task A -> task B -> finally task C. The finally task C wants to perform a different logic if either task A or task B fails. In our case, the pipeline topology is fixed and the finally task C can enumerate over the status of its previous two tasks. However, like others suggested, aggregate information would be useful and save the task C the enumeration job.

I mainly wonder if this feature is being currently worked on and if so, how I can track its progress

**Comment by jerop** [comment]
> I mainly wonder if this feature is being currently worked on and if so, how I can track its progress

@riceluxs1t a [proposal](https://github.com/tektoncd/community/blob/master/teps/0028-task-execution-status-at-runtime.md) by @pritidesai was accepted and she [implemented](https://github.com/tektoncd/pipeline/pull/3390) it already

**Comment by riceluxs1t** [comment]
@jerop ty for pointing this out. Will this be included in the next minor version release 0.20.0? Or could this be part of 0.19.x?

**Comment by pritidesai** [comment]
@riceluxs1t this will not be part of 0.19.x, we avoid introducing features in a patch release. It can be part of 0.20 depending on the reviews. I have added it to the 0.20 milestone for now.

**Comment by pritidesai** [comment]
> Hi. We also have a use case where a Tekton pipeline consists of task A -> task B -> finally task C. The finally task C wants to perform a different logic if either task A or task B fails. In our case, the pipeline topology is fixed and the finally task C can enumerate over the status of its previous two tasks. However, like others suggested, aggregate information would be useful and save the task C the enumeration job.
> 
> I mainly wonder if this feature is being currently worked on and if so, how I can track its progress

@riceluxs1t aggregate status is still not implemented. PR #3390 has implementation of accessing individual task (task A and task B in your use case and have finally task C enumerate on task A and task B).

I will have a TEP this week to propose enumerated status of all `DAG` tasks.

**Comment by riceluxs1t** [comment]
@pritidesai an ability for a finally task to access the status of individual tasks is sufficient for my use case but thank you for giving me this kind update on the progress

**Comment by jrcast** [comment]
@pritidesai is there a way to get the aggregate of all tasks? Based on #3390 it seems we have to spell out each task.

**Comment by pritidesai** [comment]
yes it is spelling out each task for now 🙃 . I am in process of proposing `aggregate` status. Please expect TEP followed by implementation PR.

**Comment by pritidesai** [comment]
/reopen 

PR #3390 introduced a part of this feature, we are still working on it.

**Comment by pritidesai** [comment]
@riceluxs1t can you please review the proposal https://github.com/tektoncd/community/pull/371 and let me know if it matches your expectations? 🙏

**Comment by pritidesai** [comment]
Reopening again 😜  since we do not expose the entire metadata yet, so far we have access to execution status of individual `pipelineTask` from the `tasks` section and an aggregate status of the entire `tasks` section, documented [here](https://github.com/tektoncd/pipeline/blob/main/docs/variables.md#variables-available-in-a-pipeline).
