### ISSUE TITLE
Tekton admission webhook complains about the when clause in my pipeline

### ISSUE THREAD

**Issue by DrissiReda** [tektoncd/pipeline#4211]
I'm using these versions of tekton

<details>
<summary> tekton images tags </summary>

```
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.23.0
gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.23.0
gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard:v0.13.0
gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/controller:v0.13.0
gcr.io/tekton-releases/github.com/tektoncd/triggers/cmd/webhook:v0.13.0
```
</details>

When I try to add this pipeline:

<details>
<summary> pipeline </summary>

```yaml
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-deploy-conditional-pipeline
  namespace: processing
spec:
  params:
    - default: http://gitea-http.ci:3000/user/sample-app
      description: Git repository url
      name: gitUrl
      type: string
    - default: master
      description: Git revision to check out
      name: gitRevision
      type: string
  tasks:
    - name: clone-repo
      params:
        - name: url
          value: $(params.gitUrl)
        - name: revision
          value: $(params.gitRevision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
    - name: retrieve-metadata
      runAfter:
      - clone-clone
      taskRef:
        kind: Task
        name: parse-metadata
      workspaces:
      - name: git
        workspace: git-source
    - when:
      - input: $(tasks.retrieve-metadata.results.codeLang)
        operator: in
        values:
        - "golang"
      name: build-code
      params:
        - name: package
          value: ''
        - name: name
          value: $(params.gitUrl)
        - name: image
          value: $(tasks.retrieve-metadata.results.buildImg)
      runAfter:
        - clone-repo
      taskRef:
        kind: Task
        name: golang-build
      workspaces:
        - name: source
          workspace: git-source
```

</details>

When I try to add this to my kubernetes dashboard, I get this error:

```
admission webhook "webhook.pipeline.tekton.dev" denied the request: mutation failed: cannot decode incoming new object: json: unknown field "when" 
```

I'm only going off of [this](https://github.com/tektoncd/pipeline/blob/main/examples/v1beta1/pipelineruns/pipelinerun-with-when-expressions.yaml#L47-L68) link. 

Is there any reason that my when clause isn't working?

**Comment by vdemeester** [comment]
@DrissiReda Hello 👋🏼 
The `when` field is only available in `v1beta1` api version ; looking at your pipeline, it seems you are using `apiVersion: tekton.dev/v1alpha1`, which is the reason why it is not allowed. Switching it to `v1beta1` should fix the problem (but be aware of [migration between v1alpha1 and v1beta1](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1alpha1-to-v1beta1.md))

**Comment by DrissiReda** [comment]
@vdemeester thank you very much ! Any idea about when this is supposed to hit alpha? Also do you have a fixed delivery cycle ? So I can look out for updates.

**Comment by vdemeester** [comment]
> @vdemeester thank you very much ! Any idea about when this is supposed to hit alpha? Also do you have a fixed delivery cycle ? So I can look out for updates.

It's never gonna hit alpha. The usual "cycle" of api is `v1alphaX` -> `v1betaX` -> `v1`. `v1alpha1` api version will be deprecate soon and in an year or less, it won't even be served by pipeline. As of today, anybody using `v1alpha1` api should migrate to `v1beta1`.

**Comment by DrissiReda** [comment]
Thanks, I've switched to  `v1beta1`. I'm currently trying to run pipelines-in-pipelines. I installed this: https://github.com/tektoncd/experimental/tree/main/pipelines-in-pipelines And I still get the error: 

```
Pipeline processing/build-and-deploy-conditional-pipeline can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task "go-pipeline": tasks.tekton.dev "go-pipeline" not found
```

I'm running this pipeline in a different namespace from the controller. But I've seen that the pip-run-controller uses ClusterRoles so I shouldn't have namespace restrictions.

**Comment by vdemeester** [comment]
Are custom tasks enabled on your tekton instance ? (see [here](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#customizing-the-pipelines-controller-behavior), `enable-custom-tasks`)

> I'm running this pipeline in a different namespace from the controller.

This should be the case in 99% of time. Pipeline's do not need to run in the same namespace as the controller.

**Comment by DrissiReda** [comment]
oh yeah! I didn't enable them, it works a lot better now (after adding `enable-api-fields:alpha` as well). Might be a good idea to add them to the doc of pip-in-pip

**Comment by DrissiReda** [comment]
@vdemeester could you please take a look at this? I'm kinda stuck: https://github.com/tektoncd/experimental/issues/791
